version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "asdasd"
      MYSQL_DATABASE: "group_buy_mall"
      TZ: Asia/Shanghai
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 16379:6379
    networks:
      - my-network
  redis-admin:
    image: spryker/redis-commander:0.8.0
    container_name: redis-admin
    hostname: redis-commander
    restart: always
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - my-network
    depends_on:
      redis:
        condition: service_healthy

  rocketmq:
    image: apache/rocketmq:latest
    container_name: rocketmq
    restart: always
    ports:
      - "9876:9876"
      - "10911:10911"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge